spring:
  application:
    name: tourplanner-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/tourplanner
    username: tourplanner
    password: tourplanner

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

jwt:
    secret: NITOwPvk0CRpX25yuE7V3EjQ+95AtuYl47ppB9/9jZs=
    expiration: 86400000